env:
  global:
    - CONAN_USERNAME: "sechinm"
    - CONAN_REFERENCE: "conan-aws-sdk-cpp/1.8"
    - CONAN_REMOTE: "sechinm"
    - CONAN_CHANNEL: "testing"

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6

    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8

    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60

    - <<: *linux 
      env: CONAN_CLANG_VERSIONS=10.0 CONAN_DOCKER_IMAGE=lasote/conanclang100

    - <<: *osx
      osx_image: xcode9
      env: CONAN_APPLE_CLANG_VERSIONS=9.0

    - <<: *osx
      osx_image: xcode9.3
      env: CONAN_APPLE_CLANG_VERSIONS=9.1

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh